var options={slider:{animSpeed:800,pauseTime:7E3}};function isMobile(){return 740>window.innerWidth?!0:!1}
$(window).load(function(){setTimeout(function(){$(".preloader").fadeOut({queue:!1,duration:500,complete:function(){setTimeout(function(){$("body").removeClass("preloading")},600)}})},1E3);740>window.innerWidth&&$("body").removeClass("preloading");window.MediaBox&&new MediaBox({gallery:".media-gallery",duration:500,easing:"easeOutQuint"});$(document).on({mouseenter:function(){if(0===$(this).children("span").length){var a=$("<span/>").appendTo($(this));setTimeout(function(){a.addClass("social-icon-hover")},
20)}else $(this).children("span").addClass("social-icon-hover")},mouseleave:function(){$(this).children("span").removeClass("social-icon-hover")}},"i");$("section").each(function(){var a=$(this);a.hasClass("phone-template")&&$.fn.PhoneTemplate?a.PhoneTemplate():a.hasClass("tablet-template")&&$.fn.TabletTemplate?a.TabletTemplate():a.hasClass("laptop-template")&&$.fn.LaptopTemplate?a.LaptopTemplate():a.hasClass("screenshots-template")&&$.fn.ScreenshotsTemplate?a.ScreenshotsTemplate():a.hasClass("features-template")&&
$.fn.FeaturesTemplate?a.FeaturesTemplate():a.hasClass("default-template")&&$.fn.DefaultTemplate?a.DefaultTemplate():a.hasClass("subscribe-template")&&$.fn.SubscribeTemplate&&a.SubscribeTemplate()});var c=$("body"),f=c.children("section"),a=0,e,b=$("<div/>").addClass("sections-slider-holder"),d=$("<ul/>").addClass("sections-slider");f.each(function(){var a=$("<li/>").attr({"data-title":$(this).attr("data-title")});$("<a/>").attr({href:"#"+(void 0!==$(this).attr("data-title")?$(this).attr("data-title"):
"").toLowerCase().replace(" ","-")}).appendTo(a);a.appendTo(d);a.index(0)===f.index(0)&&a.addClass("active")});d.appendTo(b);b.appendTo(c);d.children("li").on({click:function(g){g.preventDefault();a=$(this).index();$("html, body").animate({scrollTop:f.eq(a).offset().top},{queue:!1,duration:1E3,easing:"easeInOutCubic"})},mouseenter:function(){e=$("<div/>").addClass("tooltip");e.appendTo($(this));e.text($(this).attr("data-title"))},mouseleave:function(){void 0!==e&&e.remove()}});$(window).scroll(function(){var a=
$(window).scrollTop(),b=$(document).height(),c=$(window).height();f.each(function(e){$(this);var f=$(window).height(),p=$(window).height()/3,l=$(this).offset().top;l>a-f&&(l<a+p||a+c>=b)&&d.children("li").removeClass("active").eq(e).addClass("active")})})});
(function(c){jQuery.fn.PhoneTemplate=function(){function f(){b.each(function(){var a=c(this).height(),b=d.height()/2;c(this).css({top:b-a/2})})}var a=c(this),e=a.find(".riseSlider"),b=a.find(".riseCaptions li"),d=a.find(".section-wrapper");a.find(".riseSlider img").each(function(){c(this).addPerspective(33,27).addClass("processed")});var g=e.RiseSlider({animSpeed:options.slider.animSpeed,animEasing:"swing",pauseTime:options.slider.pauseTime,controlNav:".slider-wrapper-nav a",autoAdvance:!0});g.before=
function(){b.eq(g.current).css({display:"block"}).children().not("br").each(function(a){c(this).css({position:"relative"}).delay(80*a).animate({left:-50,opacity:0},{queue:!0,duration:500,specialEasing:{left:"easeOutCubic",opacity:"easeOutExpo"}})})};g.after=function(){var a=b.eq(g.animatingFrom),d=b.eq(g.current);a.hide();d.css({display:"block"}).children().not("br").each(function(a){c(this).css({position:"relative",opacity:0,left:-50}).delay(50*a).animate({left:0,opacity:1},{queue:!0,duration:500,
specialEasing:{left:"easeOutCubic",opacity:"easeOutExpo"}})})};f();c(window).resize(f)};jQuery.fn.TabletTemplate=function(){function f(){b.each(function(){var a=c(this).height(),b=d.height()/2;c(this).css({top:b-a/2})})}var a=c(this),e=a.find(".riseSlider"),b=a.find(".riseCaptions li"),d=a.find(".section-wrapper");a.find(".riseSlider img").each(function(){c(this).addPerspective(38,35).addClass("processed")});var g=e.RiseSlider({animSpeed:options.slider.animSpeed,animEasing:"swing",pauseTime:options.slider.pauseTime,
controlNav:".slider-wrapper-nav a",autoAdvance:!0});g.before=function(){b.eq(g.current).css({display:"block"}).children().not("br").each(function(a){c(this).css({position:"relative"}).delay(80*a).animate({left:-50,opacity:0},{queue:!0,duration:500,specialEasing:{left:"easeOutCubic",opacity:"easeOutExpo"}})})};g.after=function(){var a=b.eq(g.animatingFrom),d=b.eq(g.current);a.hide();d.css({display:"block"}).children().not("br").each(function(a){c(this).css({position:"relative",opacity:0,left:-50}).delay(50*
a).animate({left:0,opacity:1},{queue:!0,duration:500,specialEasing:{left:"easeOutCubic",opacity:"easeOutExpo"}})})};f();c(window).resize(f)};jQuery.fn.LaptopTemplate=function(){var f=c(this),a=f.find(".riseSlider"),e=f.find(".riseCaptions li"),b=a.RiseSlider({animSpeed:options.slider.animSpeed,animEasing:"swing",pauseTime:options.slider.pauseTime,controlNav:".slider-wrapper-nav a",autoAdvance:!0});b.before=function(){var a=e.eq(b.current);a.css({display:"block"}).children().each(function(b){c(this).css({position:"relative"}).delay(100*
b).animate({left:-25,opacity:0},{queue:!0,duration:500,specialEasing:{left:"easeOutCubic",opacity:"easeOutExpo"},complete:function(){a.hide()}})})};b.after=function(){e.eq(b.current).css({display:"block"}).children().each(function(a){c(this).css({position:"relative",opacity:0,left:-25}).delay(100*a).animate({left:0,opacity:1},{queue:!0,duration:500,specialEasing:{left:"easeOutCubic",opacity:"easeOutExpo"}})})}};jQuery.fn.RiseSlider=function(f){var a=c(this);a.current=0;a.canAdvance=!0;a.animatingTo=
0;a.animatingFrom=0;a.start=function(){};a.before=function(){};a.after=function(){};var e,b=c.extend({},{animSpeed:500,animEasing:"swing",pauseTime:3E3,controlNav:".slider-wrapper-nav a",autoAdvance:!0},f),d=a.find("img");d.css({"z-index":0,opacity:0}).eq(0).css({"z-index":d.length-1,opacity:1});a.play=function(){e=setInterval(function(){a.next()},b.pauseTime)};a.stop=function(){clearInterval(e)};a.next=function(){a.current<d.length-1?a.slideTo(a.current+1):a.slideTo(0);a.stop();a.play()};a.prev=
function(){0<a.current?a.slideTo(a.current-1):a.slideTo(d.length-1);a.stop();a.play()};a.slideTo=function(c){a.current!==c&&a.canAdvance&&(a.animatingTo=c,a.before(),a.canAdvance=!1,d.eq(c).css({"z-index":d.length-2,opacity:1}),d.eq(a.current).css({"z-index":d.length-1}).animate({opacity:0},{queue:!1,duration:b.animSpeed,easing:b.animEasing,complete:function(){d.eq(c).css({"z-index":d.length-1});d.eq(a.current).css({"z-index":0});a.canAdvance=!0;a.after();a.animatingFrom=c}}),a.current=c)};c(document).on("click",
b.controlNav,function(b){b.preventDefault();c(this).hasClass("next")?a.next():c(this).hasClass("prev")&&a.prev()});b.autoAdvance&&a.play();a.start();return a};jQuery.fn.addPerspective=function(f,a){var e=c(this);if(c(this).is("img")){if(void 0!==f&&void 0!==a){var b=e.width(),d=e.height(),g=c("<canvas/>").attr({width:b,height:d+(f-a)})[0];if(window.HTMLCanvasElement){for(var m=g.getContext("2d"),n=e[0],h=0;h<b;h++){var k=100*h/b;m.drawImage(n,h,0,1,d,h+1,k*f/100,1,d-k*a/100)}b=g.toDataURL("image/png",
1);e.attr({src:b})}}return e}throw"addPerspective method can only be applied to images!";}})(jQuery);function isIE(){return-1!==navigator.appVersion.indexOf("MSIE")?parseFloat(navigator.appVersion.split("MSIE")[1]):-1};